select count(*) from clasificacion;
select count(*) from categoria;
select count(*) from pelicula;
select count(*) from pais;
select count(*) from ciudad;
select count(*) from direccion;
select count(*) from tienda;
select count(*) from actor;
select count(*) from actorpelicula;
select count(*) from categoriapelicula;
select count(*) from cliente;
select count(*) from empleado;
select count(*) from inventario;
select count(*) from puesto;
select count(*) from renta;
select count(*) from traduccion
